### ISSUE TITLE
Duplicate leaders

### ISSUE THREAD

**Issue by carlin-q-scott** [AutomatedArchitecture/SirenOfShame#67] opened 2016-01-06 18:38 UTC
I was seeing several people repeated multiple times consecutively on the Leaders list. One person was there 3 times in a row, another 5 times. After restarting the application, only one person is repeated once, but with a different icon. And after waiting a while duplicates came back.

**Comment by Sennevds** [comment] 2016-01-21 13:07
Same problem,
I've looked at the code and I think if you watch several builds you get 1 leader per watched build

**Comment by lprichar** [comment] 2016-01-21 19:43
@carlin-q-scott: I like @Sennevds theory, are you watching multiple build servers?  If, even immediately after a restart, you're seeing duplicate users it could be a case issue.  Have you tried merging the accounts you see after a restart?  Merge is accomplished by right clicking on users.

**Comment by carlin-q-scott** [comment] 2016-01-22 00:22
I get this behavior from watching multiple builds from a single build server. If a person triggers multiple builds then their name is repeated.

**Comment by Sennevds** [comment] 2016-01-22 07:24
If i restart I only see one leader per person but the problem is that if someone has a successful build from one build server and than from another build it doens't add points but just adds another leader instead of adding a point. I'm trying to fix it with a local build but haven't found a solution(And it takes a long time because I work in a big company and can't force builds :))

**Comment by lprichar** [comment] 2016-02-03 01:54
This should be fixed in master.  Feel free to pull else I'll be getting a new build out for everyone shortly.  Please reopen if you're still seeing issues after getting the fix.

**Closed by lprichar** 2016-02-03 01:54 UTC

**Comment by lprichar** [comment] 2016-03-24 01:17
This fix is incorporated into 2.4.5 http://sirenofshame.com/downloads/View?downloadId=40
